### ISSUE TITLE
Where can we get the "output/r2_101.pkl in config files?

### ISSUE THREAD

**Issue by caiichenr** [xingyizhou/CenterNet2#10]
Thanks for your awesome work! Should there be a download link for 'r2_101.pkl'?

**Comment by xingyizhou** [comment]
Hi, the link is [here](https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/EZhtWgMRlxpGtJmtJ2zP1_QBqvmu_FJ05vUgOq30ElT9yg?e=e5FRD8). It can be found in the middle of the [Res2Net repo](https://github.com/Res2Net/Res2Net-detectron2).
