### ISSUE TITLE
about the demo.py

### ISSUE THREAD

**Issue by weiddyaqhhya** [xingyizhou/CenterNet2#13]
when I run the demo, it put the problems as follows:
WARNING [03/19 18:46:45 d2.config.compat]: Config 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' has no VERSION. Assuming it to be compatible with latest v2.
and:
AssertionError: Checkpoint output/r2_101.pkl not found!
I am a beginer, and actually don't know what's that mean, so can you tell me how to solve it?
oh now I know where to download r2_101.pkl, but I don't the root path to set it, The root directory of the file ？

**Comment by weiddyaqhhya** [comment]
> when I run the demo, it put the problems as follows:
> WARNING [03/19 18:46:45 d2.config.compat]: Config 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' has no VERSION. Assuming it to be compatible with latest v2.
> and:
> AssertionError: Checkpoint output/r2_101.pkl not found!
> I am a beginer, and actually don't know what's that mean, so can you tell me how to solve it?
> oh now I know where to download r2_101.pkl, but I don't the root path to set it, The root directory of the file ？

**Comment by weiddyaqhhya** [comment]
> when I run the demo, it put the problems as follows:
> WARNING [03/19 18:46:45 d2.config.compat]: Config 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' has no VERSION. Assuming it to be compatible with latest v2.
> and:
> AssertionError: Checkpoint output/r2_101.pkl not found!
> I am a beginer, and actually don't know what's that mean, so can you tell me how to solve it?
> oh now I know where to download r2_101.pkl, but I don't the root path to set it, The root directory of the file ？

**Comment by weiddyaqhhya** [comment]
> when I run the demo, it put the problems as follows:
> WARNING [03/19 18:46:45 d2.config.compat]: Config 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' has no VERSION. Assuming it to be compatible with latest v2.
> and:
> AssertionError: Checkpoint output/r2_101.pkl not found!
> I am a beginer, and actually don't know what's that mean, so can you tell me how to solve it?
> oh now I know where to download r2_101.pkl, but I don't the root path to set it, The root directory of the file ？



> when I run the demo, it put the problems as follows:
> WARNING [03/19 18:46:45 d2.config.compat]: Config 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' has no VERSION. Assuming it to be compatible with latest v2.
> and:
> AssertionError: Checkpoint output/r2_101.pkl not found!
> I am a beginer, and actually don't know what's that mean, so can you tell me how to solve it?
> oh now I know where to download r2_101.pkl, but I don't the root path to set it, The root directory of the file ？

**Comment by NguyenVanThanhHust** [comment]
@weiddyaqhhya  did you solve this problem?
