### ISSUE TITLE
What does coco_un_yolov4_55_0.5 mean

### ISSUE THREAD

**Issue by moyans** [xingyizhou/CenterNet2#2]

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest in our work. This is the pseudo-label file we used in training. It means the images are from **COCO** **un**supervised set (downloaded form [here](https://cocodataset.org/#download)). We apply Scaled**YoloV4** model with **55** mAP (YOLOv4-large [here](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-large)). We set detections with score > **0.5** as new bounding box annotations.
