### ISSUE TITLE
What is the difference between centernet.py and centernet_back.py

### ISSUE THREAD

**Issue by lxtGH** [xingyizhou/CenterNet2#20]
Hi! Thanks for opensourcing the great work. I wonder What is the difference between centernet.py and centernet_back.py?

**Comment by xingyizhou** [comment]
Thank you for catching this! This is an intermediate version during the code cleanup, that is very hard to read. I should have removed this ...

**Comment by lxtGH** [comment]
Thanks for your reply.! I got it.
