### ISSUE TITLE
KeyError: 'Non-existent config key: MODEL.ROI_BOX_HEAD.MULT_PROPOSAL_SCORE'

### ISSUE THREAD

**Issue by lbf4616** [xingyizhou/CenterNet2#30]
when I am trying to train the center2 with my own data, here is an error. 

 File "/home/atesi3/anaconda3/envs/torch18/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.ROI_BOX_HEAD.MULT_PROPOSAL_SCORE'

Which version of the yacs did you use? or which version of the detectron2? Plese help.

**Comment by xingyizhou** [comment]
Hi,
  `MODEL.ROI_BOX_HEAD.MULT_PROPOSAL_SCORE` is defined in CenterNet2 specific config [here](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/centernet/config.py). If you are using CenterNet2 models in your own detectron2 project, you need to add the path and configs like [here](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/train_net.py#L174).

**Comment by lbf4616** [comment]
> Hi,
> `MODEL.ROI_BOX_HEAD.MULT_PROPOSAL_SCORE` is defined in CenterNet2 specific config [here](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/centernet/config.py). If you are using CenterNet2 models in your own detectron2 project, you need to add the path and configs like [here](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/train_net.py#L174).

Thx, this solved the problem.

**Comment by sunset326** [comment]
How did you solve the problem?i have the same problem,need help.

   raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.BIFPN'

**Comment by Bin-ze** [comment]
在tools下的trian函数下123行添加    add_centernet_config(cfg)在头文件中引入    from projects.CenterNet2.centernet.config import add_centernet_config 你可以尝试一下

**Comment by JamesYang568** [comment]
same problem
