### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by Algo-sori** [xingyizhou/CenterNet2#4]
Hi.
Does centernet2 work in a Windows environment, not a virtual environment?

**Comment by xingyizhou** [comment]
Hi,
  Yes I have successfully installed it on a Windows machine by searching at the detectron2 issues. However I don't have the specific steps to do so. It requires several necessary code changes. Please take a look [here](https://github.com/facebookresearch/detectron2/issues/9). I am happy to help if you meet any specific errors.
