### ISSUE TITLE
what is the suitable iter for my dataset

### ISSUE THREAD

**Issue by Lg955** [xingyizhou/CenterNet2#41]
## 📚 Documentation

I have 10000 images and 5 classes, what is the suitable MAX_ITER for training Centernet2?

**Comment by xingyizhou** [comment]
Hi,
  Thank you for your interest. This is an empirical question and I don't have a clear answer. If you have a validation set, you can turn on TEST.EVAL_PERIOD to visualize the validation curve.

**Comment by Lg955** [comment]
I have trained it for 6w iters, but I think it is not enough, maybe it need 10w or more.  Thank you！
