### ISSUE TITLE
demo.py bug

### ISSUE THREAD

**Issue by CVUsers** [xingyizhou/CenterNet2#6]
(base) E:\cver>python CenterNet2-master/demo/demo.py --config-file CenterNet2-master/configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST
.yaml --input E:\cver\images\01_University_Canteen/ --opts MODEL.WEIGHTS CenterNet2-master/configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1
560_ST.pth
[03/18 13:27:40 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='CenterNet2-master/configs/CenterNet2_R2-101-D
CN-BiFPN_4x+4x_1560_ST.yaml', input=['E:\\cver\\images\\01_University_Canteen/'], opts=['MODEL.WEIGHTS', 'CenterNet2-master/configs/Ce
nterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.pth'], output=None, video_input=None, webcam=False)
Traceback (most recent call last):
  File "CenterNet2-master/demo/demo.py", line 83, in <module>
    cfg = setup_cfg(args)
  File "CenterNet2-master/demo/demo.py", line 28, in setup_cfg
    cfg.merge_from_file(best_config)
  File "e:\cver\detectron2\detectron2\config\config.py", line 30, in merge_from_file
    assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file 'configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml' does not exist!

**Comment by xingyizhou** [comment]
Hi,
  Can you check if the config path is correct? By default, it should be under "CenterNet2-master/**projects/CenterNet2**/configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST". Also, by default our code should be run under the CenterNet2 root directory. I.e.,

~~~
cd CenterNet2-master
python projects/CenterNet2/demo/demo.py --config-file projects/CenterNet2/configs/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.yaml --input E:\cver\images\01_University_Canteen/* --opts MODEL.WEIGHTS models/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.pth
~~~
