### ISSUE TITLE
CenterNet2_DLA-BiFPN-P5_640_24x_ST Config Missing

### ISSUE THREAD

**Issue by bakerada** [xingyizhou/CenterNet2#63]
## 📚 Documentation

It looks like CenterNet2_DLA-BiFPN-P5_640_24x_ST config is missing and the link in the ModelZoo table is broken [config](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/configs/CenterNet2_DLA-BiFPN-P5_640_24x_ST.yaml ). Is this configuration deprecated?

**Comment by xingyizhou** [comment]
Hi,
  Sorry for the inconvenience and the late response. It should be a typo in the documentation. The model is trained with a `16x` schedule with [this](https://github.com/xingyizhou/CenterNet2/blob/master/projects/CenterNet2/configs/CenterNet2_DLA-BiFPN-P5_640_16x_ST.yaml) config.

**Comment by bakerada** [comment]
Thank you!
