### ISSUE TITLE
What does agn_hm stand for?

### ISSUE THREAD

**Issue by chorongi** [xingyizhou/CenterNet2#89]
## 📚 Documentation Issue

This issue category is for problems about existing documentation, not for asking how-to questions.

Hello. I looked through the repository but could not find out what agn_hm stands for. I also looked through the CenterNet paper but could not find what this stands for. 

The layer definition is in `CenterNetHead` when `self.with_agn_hm = True` and it is usually just one layer of `Conv2d` with `stride = 1`. 

What is the purpose of agn_hm?

When do we need it? and when do we not need it?

Thanks in advance.

**Comment by xdjiangkai** [comment]
Hi, it seems that 'agn_hm' stands for "adaptive Gaussian heatmap". It is a type of heatmap used in object detection tasks to indicate the presence and location of an object in an image.

**Comment by chorongi** [comment]
Thank you so  much for the explanation @xdjiangkai .

**Comment by chorongi** [comment]
@xdjiangkai
